### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by dossantg** [HeinleinSupport/razorfy#3]
Hello,

Thanks for this code which works great with rspamd!

We are seeing a constant increase in memory consumption.

Have you ever seen this?

Best regards

**Comment by cbay** [comment]
I can confirm the issue, which apparently comes from `Razor2::Client::Agent` itself (commenting the `$agent->checkit` line resolves the crazy memory usage).

However, in case you didn't know, Razorfy usage is deprecated by rspamd, which [recommends using `razor-check`]($agent->checkit) directly (over systemd).

**Comment by dossantg** [comment]
Tanks for your feedback.
